/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background:               '#F7F4EF',
        surface:                  '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low':  '#FBF9F5',
        'surface-container':      '#F2EDE6',
        'surface-container-high': '#EBE4DA',
        'surface-container-highest': '#E5DED6',
        'surface-bright':         '#FFFFFF',
        primary:                  '#D97757',
        'primary-container':      '#F9ECE7',
        'on-primary':             '#FFFFFF',
        'on-primary-container':   '#7A2F15',
        'primary-fixed':          '#FFDBD0',
        'primary-fixed-dim':      '#FFB59E',
        secondary:                '#6B625B',
        'secondary-container':    '#EDE0D7',
        'on-secondary-container': '#4D453F',
        tertiary:                 '#B87A36',
        'tertiary-container':     '#F6EFE6',
        'tertiary-fixed-dim':     '#D0C4BC',
        'on-surface':             '#2D2926',
        'on-surface-variant':     '#6B625B',
        outline:                  '#88726C',
        'outline-variant':        '#E5DED6',
        error:                    '#C34A4A',
        'error-container':        '#FDF0F0',
        'on-error-container':     '#851D1D',
        // status aliases
        'status-success':         '#5B7C4B',
        'status-error':           '#C34A4A',
        'status-warning':         '#B87A36',
        // accent shortcuts
        'accent-primary':         '#D97757',
        'accent-hover':           '#C66849',
        'accent-deep':            '#99462A',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'space-2xs':  '0.125rem',
        'space-xs':   '0.25rem',
        'space-sm':   '0.5rem',
        'space-md':   '0.75rem',
        'space-base': '1rem',
        'space-lg':   '1.5rem',
        'space-xl':   '2rem',
        'space-2xl':  '3rem',
      },
      fontFamily: {
        'headline-xl':    ['"Space Grotesk"', 'Inter', 'sans-serif'],
        'headline-lg':    ['"Space Grotesk"', 'Inter', 'sans-serif'],
        'headline-md':    ['"Space Grotesk"', 'Inter', 'sans-serif'],
        'headline-sm':    ['"Space Grotesk"', 'Inter', 'sans-serif'],
        'body-lg':        ['Manrope', 'Inter', 'sans-serif'],
        'body-md':        ['Manrope', 'Inter', 'sans-serif'],
        'body-sm':        ['Manrope', 'Inter', 'sans-serif'],
        'label-caps':     ['"JetBrains Mono"', 'monospace'],
        'label-code-md':  ['"JetBrains Mono"', 'monospace'],
        'label-code-sm':  ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-xl':  ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg':  ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md':  ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm':  ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg':      ['16px', { lineHeight: '26px', letterSpacing: '0em',     fontWeight: '400' }],
        'body-md':      ['14px', { lineHeight: '22px', letterSpacing: '0.01em',  fontWeight: '400' }],
        'body-sm':      ['12px', { lineHeight: '18px', letterSpacing: '0.01em',  fontWeight: '400' }],
        'label-caps':   ['10px', { lineHeight: '14px', letterSpacing: '0.08em',  fontWeight: '600' }],
        'label-code-md':['12px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-code-sm':['11px', { lineHeight: '16px', letterSpacing: '0.02em',  fontWeight: '500' }],
      },
      keyframes: {
        fadeIn: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-out',
      },
      boxShadow: {
        card:   '0 2px 12px rgba(45,41,38,0.04)',
        panel:  '0 2px 16px rgba(45,41,38,0.04)',
        header: '0 1px 10px rgba(45,41,38,0.03)',
        sidebar:'0 1px 16px rgba(45,41,38,0.04)',
      },
    },
  },
  plugins: [],
};
